/**
 * Por cliente: `tech` son tecnologías destacadas asociadas al trabajo (portfolio),
 * no un inventario exhaustivo del stack en producción - validar con el cliente si se publicitan como "todo lo que usa".
 */
const casesMeta = [
  {
    name: 'Inquilia',
    url: 'https://inquilia.com',
    logo: '/logos/inquilia.svg',
    tech: [
      'Next.js',
      'i18n',
      'Tailwind',
      'Supabase',
      'CryptoJS',
      'AES-256',
      'Formik',
      'Yup',
      'Vercel',
      'Resend',
      'TanStack Query',
      'Sentry',
    ],
  },
  {
    name: 'CD648',
    url: 'https://cd648.com',
    logo: '/logos/cd648.svg',
    logoFrame: 'landscape',
    tech: [
      'React',
      'Stripe',
      'i18n',
      'Google Maps API',
      'MongoDB',
      'Express',
      'Node.js',
      'Framer Motion',
      'Formik',
      'Yup',
      'Tailwind',
      'Custom Hooks',
      'Sentry',
    ],
  },
  {
    name: 'Quimialcla',
    url: 'https://quimialcla.com.mx',
    logo: '/logos/quimialcla.svg',
    logoFrame: 'landscape',
    tech: [
      'React',
      'Tailwind',
      'i18n',
      'Vercel',
      'HTML/CSS',
      'Custom Hooks',
      'Sentry',
    ],
  },
  {
    name: 'Morningstar',
    url: 'https://morningstar.lat',
    logo: '/logos/morningstar.svg',
    tech: [
      'Next.js',
      'Tailwind',
      'Contentful',
      'Vercel',
      'CI/CD',
      'TanStack Query',
      'Radix UI',
    ],
  },
  {
    name: 'AMIDA',
    url: 'https://amida.com.mx',
    logo: '/logos/amida.svg',
    logoFrame: 'landscape',
    tech: [
      'Next.js',
      'Tailwind',
      'Framer Motion',
      'i18next',
      'Keen Slider',
      'EmailJS',
      'Zod',
      'Radix UI',
    ],
  },
  {
    name: 'Suitable',
    url: 'https://www.suitable.mx',
    logo: '/logos/suitable.svg',
    // Destacados acordes al tipo de producto (ops / propiedades); el producto puede usar más servicios internamente.
    tech: [
      'Next.js',
      'React',
      'TypeScript',
      'Tailwind',
      'Supabase',
      'Vercel',
      'Framer Motion',
      'Stripe',
      'Zod',
      'TanStack Query',
      'Sentry',
      'Radix UI',
    ],
  },
  {
    name: 'YOU.',
    url: 'https://www.yousoluciones.com',
    logo: '/logos/you-soluciones-inmobiliarias.svg',
    tech: [
      'Next.js',
      'Tailwind',
      'i18n',
      'Vercel',
      'Framer Motion',
      'Zod',
      'Sentry',
    ],
  },
];

export default casesMeta;